src/todofeature/urls.py
from django.urls import path
from todofeature.views import todo_list_view, todo_add_view, todo_edit_view


app_name = "todofeature"
urlpatterns = [
    path("", todo_list_view, name="todo_list"),
    path("todo-add/", todo_add_view, name="todo_add"),
    path("todo-edit/<int:taskid>/", todo_edit_view, name="todo_edit"),
]

src/todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todofeature.urls", namespace="todofeature"))
]

src/todofeature/models.py
from django.db import models


class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# Create your models here.
class Category(TimeStamp):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Label(TimeStamp):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Priority(models.TextChoices):
    LOWEST = "lowest", "Lowest"
    LOW = "low", "Low"
    MEDIUM = "medium", "Medium"
    HIGH = "high", "High"
    HIGHEST = "highest", "Highest"


class Task(TimeStamp):
    name = models.CharField(max_length=255)
    description = models.TextField(
        blank=True,
        null=True,
    )
    image = models.ImageField(
        upload_to="todoimg/",
        blank=True,
        null=True,
    )
    task_time = models.DateField(
        blank=True,
        null=True,
    )
    priority = models.CharField(
        max_length=100,
        choices=Priority.choices,
        default=Priority.LOWEST,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    labels = models.ManyToManyField(
        Label,
        blank=True,
    )
    is_done = models.BooleanField(default=False)

    def __str__(self):
        return self.name

src/useraccount/models.py
from django.db import models

# Create your models here.

src/todofeature/forms.py
from django import forms
from todofeature.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields["name"].widget.attrs["class"] = "form-control"
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            # self.fileds()

        # exclude = ("image",)   to exclude unnecessary fields
        # fields = ("name", "description", ) to include only necessary fields

    def clean_name(self):  # to validate specific filed
        name = self.cleaned_data.get("name")
        if name.isdigit():
            raise forms.ValidationError("Name cannot be in numbers")
        return name
        

src/todofeature/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from todofeature.models import Task
from todofeature.forms import TaskForm
from django.http import HttpResponseRedirect, HttpResponse


# Create your views here.
def todo_list_view(request):
    tasks = Task.objects.all().order_by("priority")
    context = {"tasks": tasks}
    return render(request, "todo_list.html", context)


def todo_add_view(request):
    form = TaskForm(request.POST or None)
    if form.is_valid():
        # print(form.cleaned_data)
        form.save()
        return HttpResponseRedirect(reverse("todofeature:todo_list"))
    return render(request, "add_todo.html", {"form": form})


def todo_edit_view(request, taskid):
    task = get_object_or_404(Task, id=taskid)

    # above code means
    # try:
    #     Task.objects.get(id=taskid)
    # except Task.DoesNotExist:
    #     return Http404()

    form = TaskForm(request.POST or None, instance=task)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse("todofeature:todo_list"))
    return render(request, "add_todo.html", {"form": form})

src/useraccount/views.py
from django.shortcuts import render

# Create your views here.

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% if title %}
            {{ title }}
        {% else %}
            TODO 
        {% endif %}
    </title>
    {% block stylesheet %}
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    {% endblock stylesheet %}
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

src/templates/base_site.html
{% extends 'base.html' %}
{% block content %}
    {% include 'navbar.html' %}

    {% block maincontent %}

    {% endblock maincontent %}

{% endblock content%}

src/templates/navbar.html
<ul>
    <li>
        <a href="{% url 'todofeature:todo_list' %}">List Todo</a>
    </li>
    <li>
        <a href="{% url 'todofeature:todo_add' %}">Add Todo</a>
    </li>
</ul>

src/todofeature/templates/add_todo.html
{% extends 'base_site.html' %}


{% block maincontent %}
<form method="post" action=""> {% csrf_token%}
   {{ form.as_p }}
   <!-- {{ form.non_field_errors }} -->
   <!-- <div class="fieldWrapper my-2">
       {{ form.name.errors }}
       <label for="{{ form.name.id_for_label }}">Name:</label>
       {{ form.name }}
   </div>
   <div class="fieldWrapper my-2">
       {{ form.description.errors }}
       <label for="{{ form.description.id_for_label }}">Description:</label>
       {{ form.description }}
   </div>
   <div class="fieldWrapper my-2*">
       {{ form.priority.errors }}
       <label for="{{ form.priority.id_for_label }}">Priority:</label>
       {{ form.priority }}
   </div> -->
   

   <input name="submit" value="Submit" type="submit"/>
</form>
{% endblock maincontent %}

src/todofeature/templates/todo_list.html
{% extends 'base_site.html' %}

{% block maincontent%}
<h1> My Todo List</h1>
<table class="table table-striped table-bordered" border="6">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Priority</th>
        </tr>
    </thead>
    <tbody>
        {% for task in tasks %}
            <tr>
                <td>
                    <a href="{% url 'todofeature:todo_edit' task.id %}">{{task.name}}</a> 
                    </td>
                <td>{{task.description}}</td>
                <td>{{task.priority}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock maincontent %}